# Generated by Django 3.0.4 on 2020-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200317_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Видна всем'),
        ),
    ]
